### ISSUE TITLE
Pre-start script chmod path

### ISSUE THREAD

**Issue by MitchTalmadge** [gardner/tv#1]
Hey there,

I am trying to get my on-complete script running similar to yours (I saw your post in the transmission-openvpn docker repo). Just curious, your pre-start script seems to be chmod'ing a script at /on-complete.sh (root level dir) but in your docker-compose it is placed inside of /scripts, not at /. Am I missing something?

Thanks!

https://github.com/gardner/tv/blob/20a5afcfeb13cdca56ca1aa04091a9c3d8f7d169/scripts/transmission-pre-start.sh#L3

https://github.com/gardner/tv/blob/20a5afcfeb13cdca56ca1aa04091a9c3d8f7d169/docker-compose.yml#L130

**Comment by gardner** [comment]
That looks like a bug. Thanks for pointing it out. It's been fixed in https://github.com/gardner/tv/commit/7df1dd30543ac8fc916fcaff4c26c3ae2e53841d
